insert into tipo_cliente values(1,"Normal");
insert into tipo_cliente values(2,"VIP");

insert into distrito values(1,"Lima");
insert into distrito values(2,"Ancón");
insert into distrito values(3,"Ate Vitarte");
insert into distrito values(4,"Barranco");
insert into distrito values(5,"Breña");
insert into distrito values(6,"Carabayllo");
insert into distrito values(7,"Comas");
insert into distrito values(8,"Chaclacayo");
insert into distrito values(9,"Chorrillos");
insert into distrito values(10,"El Agustino");
insert into distrito values(11,"Jesús María");
insert into distrito values(12,"La Molina");
insert into distrito values(13,"La Victoria");
insert into distrito values(14,"Lince");
insert into distrito values(15,"Lurigancho");
insert into distrito values(16,"Lurín");
insert into distrito values(17,"Magdalena del Mar");
insert into distrito values(18,"Miraflores");
insert into distrito values(19,"Pachacamac");
insert into distrito values(20,"Pucusana");
insert into distrito values(21,"Pueblo Libre");
insert into distrito values(22,"Puente Piedra");
insert into distrito values(23,"Punta Negra");
insert into distrito values(24,"Punta Hermosa");
insert into distrito values(25,"Rímac");
insert into distrito values(26,"San Bartolo");
insert into distrito values(27,"San Isidro");
insert into distrito values(28,"Independencia");
insert into distrito values(29,"San Juan de Miraflores");
insert into distrito values(30,"San Luis");
insert into distrito values(31,"San Martín de Porres");
insert into distrito values(32,"San Miguel");
insert into distrito values(33,"Santiago de Surco");
insert into distrito values(34,"Surquillo");
insert into distrito values(35,"Villa María del Triunfo");
insert into distrito values(36,"San Juan de Lurigancho");
insert into distrito values(37,"Santa María del Mar");
insert into distrito values(38,"Santa Rosa");
insert into distrito values(39,"Los Olivos	");
insert into distrito values(40,"Cieneguilla");
insert into distrito values(41,"San Borja");
insert into distrito values(42,"Villa El Salvador");
insert into distrito values(43,"Santa Anita");
